on:
  push:
    tags-ignore: 
      - "v[0-9]*"
  workflow_dispatch:
    # No confing
  workflow_call:
    outputs:
      artifact-id:
        value: ${{ jobs.build.outputs.artifact-id }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build
      - run: mv "$(npm pack)" package.tgz
      - uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: package
          path: package.tgz
          if-no-files-found: error
